from __future__ import annotations

from typing import Protocol

from research_agent.domain import Evaluation, Report, ResearchRun, Session, SessionMessage, ToolCallRecord


class Repository(Protocol):
    def create_session(self, session: Session) -> None: ...
    def append_message(self, message: SessionMessage) -> None: ...
    def list_messages(self, session_id) -> list[SessionMessage]: ...
    def create_research_run(self, run: ResearchRun) -> None: ...
    def update_research_run(self, run: ResearchRun) -> None: ...
    def record_tool_call(self, tool_call: ToolCallRecord) -> None: ...
    def save_report(self, report: Report) -> None: ...
    def save_evaluation(self, evaluation: Evaluation) -> None: ...
